const categories = [
  {
    id: 1, name: "Heart", emoji: "❤️",
    image: "/categories/heart.jpg",
    imagePosition: "center center",
    description: "Detect cholesterol levels, cardiac risk markers and overall heart health early.",
    priceRange: "₹99 – ₹799",
    tests: [
      { name: "Lipid Profile (5 Tests)", description: "Measures total cholesterol, HDL, LDL, VLDL and triglycerides for cardiac risk.", price: 299, icon: "🫀" },
      { name: "Complete Blood Count (CBC)", description: "Full blood count covering RBC, WBC, platelets and haemoglobin levels.", price: 249, icon: "💉" },
      { name: "HbA1c", description: "Measures average blood sugar over 3 months — key marker for heart risk.", price: 299, icon: "📊" },
      { name: "Fasting Blood Sugar", description: "Measures blood glucose after fasting — screens for diabetes and cardiac risk.", price: 99, icon: "🩸" },
      { name: "SGOT / AST", description: "Detects heart muscle damage — elevated after cardiac events.", price: 199, icon: "🔬" },
      { name: "CRP (C-Reactive Protein)", description: "Inflammation marker — elevated CRP increases heart disease risk.", price: 349, icon: "🧬" },
      { name: "Homocysteine", description: "High homocysteine levels increase risk of heart attack and stroke.", price: 599, icon: "🧪" },
      { name: "Troponin I", description: "Primary marker for heart attack — detects cardiac muscle damage.", price: 799, icon: "❤️" },
      { name: "Uric Acid", description: "High uric acid is linked to increased cardiovascular disease risk.", price: 199, icon: "💊" },
      { name: "ESR (Erythrocyte Sedimentation Rate)", description: "Detects inflammation associated with heart and vascular conditions.", price: 149, icon: "🩺" },
    ]
  },
  {
    id: 2, name: "Kidney", emoji: "🫘",
    image: "/categories/kidney.jpg",
    imagePosition: "center center",
    description: "Assess kidney function and detect renal disorders at an early stage.",
    priceRange: "₹99 – ₹499",
    tests: [
      { name: "Kidney Function Test (KFT - 10 Tests)", description: "Comprehensive panel: Creatinine, Urea, BUN, Uric Acid and electrolytes.", price: 499, icon: "🫘" },
      { name: "Urine Routine & Microscopy", description: "Detects UTI, kidney disease and urinary tract disorders.", price: 149, icon: "🧪" },
      { name: "Complete Blood Count (CBC)", description: "Detects anaemia and infections linked to poor kidney function.", price: 249, icon: "💉" },
      { name: "Fasting Blood Sugar", description: "Diabetes is a leading cause of kidney damage — early detection is critical.", price: 99, icon: "🩸" },
      { name: "Uric Acid", description: "High uric acid can cause kidney stones and damage kidney tissue.", price: 199, icon: "💊" },
      { name: "Electrolytes (Na, K, Cl)", description: "Measures sodium, potassium, chloride — key markers of kidney health.", price: 349, icon: "⚡" },
      { name: "Calcium", description: "Abnormal calcium levels indicate kidney or parathyroid dysfunction.", price: 249, icon: "🦴" },
      { name: "Phosphorus", description: "High phosphorus is a sign of reduced kidney filtering capacity.", price: 249, icon: "🔬" },
      { name: "Albumin", description: "Low albumin levels may indicate kidney protein loss or malnutrition.", price: 199, icon: "🧬" },
      { name: "HbA1c", description: "Long-term blood sugar marker — key for monitoring diabetic kidney disease.", price: 299, icon: "📊" },
    ]
  },
  {
    id: 3, name: "Liver", emoji: "🟤",
    image: "/categories/liver.jpg",
    imagePosition: "center center",
    description: "Evaluate liver enzymes and detect liver disease or damage early.",
    priceRange: "₹99 – ₹599",
    tests: [
      { name: "Liver Function Test (LFT - 8 Tests)", description: "Measures SGPT, SGOT, ALP, Bilirubin and proteins for liver health.", price: 449, icon: "🟤" },
      { name: "Hepatitis B Surface Antigen (HBsAg)", description: "Detects Hepatitis B infection — a leading cause of liver disease.", price: 399, icon: "🦠" },
      { name: "Hepatitis C Antibody (Anti-HCV)", description: "Screens for Hepatitis C virus — a major cause of chronic liver disease.", price: 499, icon: "🔬" },
      { name: "Complete Blood Count (CBC)", description: "Detects anaemia and blood disorders associated with liver conditions.", price: 249, icon: "💉" },
      { name: "Gamma-GT (GGT)", description: "Sensitive marker for liver and bile duct disease and alcohol damage.", price: 299, icon: "🧪" },
      { name: "Prothrombin Time (PT/INR)", description: "Measures blood clotting — the liver makes all clotting factors.", price: 349, icon: "⏱️" },
      { name: "Albumin", description: "Produced by the liver — low levels indicate advanced liver disease.", price: 199, icon: "🧬" },
      { name: "Fasting Blood Sugar", description: "Liver plays a key role in blood sugar regulation — tested alongside LFT.", price: 99, icon: "🩸" },
      { name: "Uric Acid", description: "Liver processes purines — high uric acid can indicate liver stress.", price: 199, icon: "💊" },
      { name: "Alkaline Phosphatase (ALP)", description: "Elevated ALP signals liver, bile duct or bone disease.", price: 199, icon: "📊" },
    ]
  },
  {
    id: 4, name: "Thyroid", emoji: "🦋",
    image: "/categories/thyroid.jpg",
    imagePosition: "center top",
    description: "Check T3, T4 and TSH levels to evaluate thyroid gland function.",
    priceRange: "₹99 – ₹799",
    tests: [
      { name: "Thyroid Profile (T3, T4, TSH)", description: "Complete thyroid panel to detect hypo or hyperthyroidism.", price: 349, icon: "🦋" },
      { name: "Free T3 (FT3)", description: "Measures active thyroid hormone — more accurate than total T3.", price: 299, icon: "🔬" },
      { name: "Free T4 (FT4)", description: "Measures free thyroxine — key marker for thyroid function.", price: 299, icon: "🧬" },
      { name: "Anti-TPO Antibody", description: "Detects autoimmune thyroid disease like Hashimoto's thyroiditis.", price: 599, icon: "🛡️" },
      { name: "Anti-Thyroglobulin Antibody", description: "Identifies autoimmune attack on the thyroid gland.", price: 599, icon: "🧪" },
      { name: "Vitamin B12", description: "Thyroid disorders often cause B12 deficiency — test together.", price: 349, icon: "💊" },
      { name: "Vitamin D 25-Hydroxy", description: "Low Vitamin D is linked to autoimmune thyroid conditions.", price: 499, icon: "☀️" },
      { name: "Complete Blood Count (CBC)", description: "Thyroid disorders affect blood cells — CBC helps complete the picture.", price: 249, icon: "💉" },
      { name: "Fasting Blood Sugar", description: "Thyroid and diabetes are closely linked — test both together.", price: 99, icon: "🩸" },
      { name: "Lipid Profile", description: "Hypothyroidism raises cholesterol — lipid test recommended with thyroid.", price: 299, icon: "🫀" },
    ]
  },
  {
    id: 5, name: "Intestines", emoji: "🌀",
    image: "/categories/intestines.jpg",
    imagePosition: "center center",
    description: "Identify digestive disorders, infections and nutrient absorption issues.",
    priceRange: "₹99 – ₹499",
    tests: [
      { name: "Stool Routine & Microscopy", description: "Detects parasites, blood and bacteria in stool for gut disorders.", price: 149, icon: "🔬" },
      { name: "Stool Culture & Sensitivity", description: "Identifies bacterial infection in gut and recommends right antibiotic.", price: 399, icon: "🧫" },
      { name: "H. Pylori Antigen (Stool)", description: "Detects H. Pylori bacteria — a common cause of ulcers and gastritis.", price: 499, icon: "🦠" },
      { name: "Complete Blood Count (CBC)", description: "Detects anaemia caused by poor nutrient absorption in intestines.", price: 249, icon: "💉" },
      { name: "Liver Function Test (LFT)", description: "Liver and intestines are closely linked — tested together.", price: 449, icon: "🟤" },
      { name: "Albumin", description: "Low albumin indicates poor protein absorption in the intestines.", price: 199, icon: "🧬" },
      { name: "Calcium", description: "Intestinal diseases reduce calcium absorption causing deficiency.", price: 249, icon: "🦴" },
      { name: "Vitamin B12", description: "B12 is absorbed in the intestines — deficiency signals gut problems.", price: 349, icon: "💊" },
      { name: "Fasting Blood Sugar", description: "Blood sugar levels are affected by intestinal absorption disorders.", price: 99, icon: "🩸" },
      { name: "Urine Routine & Microscopy", description: "Rules out urinary tract involvement in abdominal symptoms.", price: 149, icon: "🧪" },
    ]
  },
  {
    id: 6, name: "Joints", emoji: "🦴",
    image: "/categories/joints.jpg",
    imagePosition: "center top",
    description: "Detect inflammation, arthritis and joint-related conditions early.",
    priceRange: "₹149 – ₹799",
    tests: [
      { name: "Uric Acid", description: "High uric acid causes gout — a painful form of inflammatory arthritis.", price: 199, icon: "💊" },
      { name: "RA Factor (Rheumatoid Arthritis Factor)", description: "Key marker for diagnosing rheumatoid arthritis and joint inflammation.", price: 299, icon: "🦴" },
      { name: "CRP (C-Reactive Protein)", description: "Sensitive inflammation marker — elevated in all forms of arthritis.", price: 349, icon: "🔥" },
      { name: "ESR (Erythrocyte Sedimentation Rate)", description: "Measures inflammation speed — elevated in arthritis and joint diseases.", price: 149, icon: "🩺" },
      { name: "Anti-CCP Antibody", description: "Highly specific marker for early rheumatoid arthritis detection.", price: 799, icon: "🛡️" },
      { name: "Vitamin D 25-Hydroxy", description: "Low Vitamin D causes bone and joint pain and increases arthritis risk.", price: 499, icon: "☀️" },
      { name: "Calcium", description: "Low calcium weakens bones and worsens joint conditions.", price: 249, icon: "🦴" },
      { name: "Complete Blood Count (CBC)", description: "Detects anaemia and infection that often accompany joint diseases.", price: 249, icon: "💉" },
      { name: "ANA (Antinuclear Antibody)", description: "Screens for autoimmune diseases like Lupus that affect the joints.", price: 699, icon: "🧬" },
      { name: "Kidney Function Test", description: "Joint medications can affect kidneys — monitor kidney health alongside.", price: 499, icon: "🫘" },
    ]
  },
  {
    id: 7, name: "Fever", emoji: "🌡️",
    image: "/categories/fever.jpg",
    imagePosition: "center center",
    description: "Identify the cause of fever — viral, bacterial or parasitic infections.",
    priceRange: "₹99 – ₹499",
    tests: [
      { name: "Complete Blood Count (CBC)", description: "First test in fever — identifies infection type: viral or bacterial.", price: 249, icon: "💉" },
      { name: "Malaria Antigen Test", description: "Rapid test to detect Plasmodium falciparum and vivax malaria.", price: 299, icon: "🦟" },
      { name: "Dengue NS1 Antigen", description: "Detects dengue virus in early stage of fever (Day 1-5).", price: 499, icon: "🦠" },
      { name: "Widal Test", description: "Diagnoses typhoid fever caused by Salmonella typhi bacteria.", price: 199, icon: "🔬" },
      { name: "CRP (C-Reactive Protein)", description: "Differentiates bacterial from viral fever — guides treatment.", price: 349, icon: "🔥" },
      { name: "ESR", description: "Elevated in prolonged fever — indicates ongoing inflammation.", price: 149, icon: "🩺" },
      { name: "Urine Routine & Microscopy", description: "Rules out urinary tract infection as a cause of fever.", price: 149, icon: "🧪" },
      { name: "Leptospira IgM", description: "Detects Leptospirosis — a bacterial infection common in monsoon.", price: 499, icon: "💧" },
      { name: "Chikungunya IgM", description: "Detects Chikungunya virus — causes high fever and severe joint pain.", price: 499, icon: "🦟" },
      { name: "Blood Culture & Sensitivity", description: "Identifies bacteria in bloodstream for severe or persistent fever.", price: 499, icon: "🧫" },
    ]
  },
  {
    id: 8, name: "Diabetes", emoji: "🩸",
    image: "/categories/diabetes.jpg",
    imagePosition: "center center",
    description: "Monitor blood sugar, HbA1c and related markers for diabetes management.",
    priceRange: "₹99 – ₹499",
    tests: [
      { name: "Fasting Blood Sugar", description: "Primary test for diagnosing diabetes and prediabetes.", price: 99, icon: "🩸" },
      { name: "Post Prandial Blood Sugar (PPBS)", description: "Blood sugar measured 2 hours after meals — detects post-meal spikes.", price: 99, icon: "🍽️" },
      { name: "HbA1c", description: "Measures 3-month average blood sugar — gold standard for diabetes.", price: 299, icon: "📊" },
      { name: "Kidney Function Test (KFT)", description: "Diabetes damages kidneys early — monitor KFT regularly.", price: 499, icon: "🫘" },
      { name: "Lipid Profile", description: "Diabetics have higher cholesterol risk — full lipid panel essential.", price: 299, icon: "🫀" },
      { name: "Urine Microalbumin", description: "Detects early kidney damage in diabetic patients.", price: 349, icon: "🧪" },
      { name: "Complete Blood Count (CBC)", description: "Anaemia is common in diabetes — CBC gives complete blood picture.", price: 249, icon: "💉" },
      { name: "Liver Function Test (LFT)", description: "Fatty liver is common in Type 2 diabetes — LFT monitors it.", price: 449, icon: "🟤" },
      { name: "Thyroid Profile (TSH)", description: "Thyroid disorders and diabetes often occur together — test both.", price: 349, icon: "🦋" },
      { name: "Vitamin D 25-Hydroxy", description: "Low Vitamin D worsens insulin resistance in diabetics.", price: 499, icon: "☀️" },
    ]
  },
  {
    id: 9, name: "Infection", emoji: "🦠",
    image: "/categories/infection.jpg",
    imagePosition: "center center",
    description: "Detect bacterial, viral and fungal infections through blood and culture tests.",
    priceRange: "₹99 – ₹699",
    tests: [
      { name: "Complete Blood Count (CBC)", description: "WBC count indicates infection type and severity — first line test.", price: 249, icon: "💉" },
      { name: "CRP (C-Reactive Protein)", description: "Distinguishes bacterial from viral infections quickly and accurately.", price: 349, icon: "🔥" },
      { name: "ESR", description: "Elevated in chronic or ongoing infections and inflammatory conditions.", price: 149, icon: "🩺" },
      { name: "Blood Culture & Sensitivity", description: "Identifies bacteria in blood for serious or persistent infections.", price: 499, icon: "🧫" },
      { name: "Urine Culture & Sensitivity", description: "Detects urinary tract infection and identifies the causative organism.", price: 399, icon: "🧪" },
      { name: "Widal Test", description: "Diagnoses typhoid fever — common bacterial infection in India.", price: 199, icon: "🔬" },
      { name: "Dengue NS1 Antigen", description: "Early detection of dengue virus infection in febrile patients.", price: 499, icon: "🦠" },
      { name: "Malaria Antigen Test", description: "Rapid detection of malaria parasite in blood — results in 30 minutes.", price: 299, icon: "🦟" },
      { name: "HBsAg (Hepatitis B Antigen)", description: "Detects active Hepatitis B infection — a viral liver infection.", price: 399, icon: "🛡️" },
      { name: "HIV Screening (ELISA)", description: "Confidential screening for HIV infection — early detection saves lives.", price: 699, icon: "🔴" },
    ]
  }
];

export default categories;
